### ISSUE TITLE
The case of multiple fileNames is not considered in modern browsers

### ISSUE THREAD

**Issue by SeahorZhang** [lujjjh/content-disposition-attachment#2]
content-disposition:"attachment; filename=xx.xlsx; filename*=utf-8''xxxx.xlsx"

//Error: duplicated field 'filename'

**Comment by lujjjh** [comment]
Thank you for reporting this, I'll take a look soon.

**Comment by lujjjh** [comment]
I released 0.2.0 which should have fixed this issue.
